# Generated by Django 4.1.7 on 2023-02-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopaccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='mp_id',
        ),
    ]
