# Generated by Django 4.1.7 on 2023-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopaccount', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
