# Generated by Django 4.1.7 on 2023-03-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopaccount', '0006_transaction_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type_name', models.CharField(max_length=200)),
                ('pay_type_perc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date created')),
                ('pay_name', models.CharField(max_length=200)),
                ('pay_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopaccount.payouttype')),
            ],
        ),
    ]
