# Generated by Django 4.1.7 on 2023-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopaccount', '0008_rename_date_payout_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_article',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
